
import Footer from './components/Footer'
import Header from './components/Navbar'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <div >
        <Header />
        </div>
        {children}
       <Footer />
        </body>
    </html>
  )
}